version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: goodpassword
      POSTGRES_USER: admin
      POSTGRES_DB: market_data
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: "D:/volumes/pgdata"
        target: "/var/lib/postgresql/data"
      #- pgdata:/var/lib/postgresql/data

volumes:
  pgdata: